### ISSUE TITLE
Documentation URLs

### ISSUE THREAD

**Issue by dhardy** [rust-random/rngs#2]
Options for documentation:

1. Keep all doc under the https://rust-random.github.io/rand/ by use of cloning the repo and hacking the Cargo.toml in the `rand` repo's Travis doc builder
2. Use only docs.rs for these crates
3. Other?

**Comment by vks** [comment]
Is there any reason to prefer 1. over 2.?

**Comment by dhardy** [comment]
Probably not. And having the `rand` repo's CI fail because of an issue in this repo would be annoying (not that there's a shortage of reasons for CI to fail).

**Comment by vks** [comment]
Then I think we should go with 2. and only use docs.rs for this repo.

**Comment by dhardy** [comment]
Want to make the PR?

**Comment by dhardy** [comment]
URLs were changed in #15.
