### ISSUE TITLE
Document that xorshift can't be seeded with zero

### ISSUE THREAD

**Issue by Minoru** [rust-random/rngs#24]
When seeded with zero, xorshift is silently seeded with a different value:

https://github.com/rust-random/rngs/blob/7cda1f86283fd7005d1a2f0471283d929bd58bfd/rand_xorshift/src/lib.rs#L86-L91

The docs don't mention this though.

When seeding from another RNG, the situation is even worse: if the seeding RNG keeps returning zeroes, xorshift's initialization will loop forever:

https://github.com/rust-random/rngs/blob/7cda1f86283fd7005d1a2f0471283d929bd58bfd/rand_xorshift/src/lib.rs#L102-L108

`from_rng` is fallible, so it could perform a limited number of iterations and fail if it can't get a non-zero seed.

I think that, at the very least, these behaviours should be documented.

**Comment by vks** [comment]
I agree that the behavior for 0 seeds should be documented. However, I disagree that we should add special code for pathological RNG implementations that always return 0. Such behavior would break a lot of code in Rand, because rejection sampling is used in many algorithms.
